### ISSUE TITLE
CQL activity shouldn't log sensitive information

### ISSUE THREAD

**Issue by alexott** [nosqlbench/nosqlbench#106]
**Describe the bug**

Right now, CQL activity logs sensitive information, such as, passwords and user names.

```
10:10:12.531 [scenarios:001] INFO  i.n.engine.core.ActivityExecutor - stopping activity CQLActivity {activityDef=ActivityDef:(1)/{cycles=1k, tspass=XXX, type=cql, tags=phase:rampup, password=XXX, host=..., truststore=key.jks, yaml=/home/db2inst1/NOSQLBENCH/qte_select.yaml, username=XXXX}, session=null, opSequence=null}
```

**To Reproduce**

run activity that connects to DSE/Cassandra cluster SSL and/or authentication enabled

**What was Expected**

sensitive information should be redacted.

**Comment by jshook** [comment]
Anything that you put on the command line should be deemed unprotected, as the CLI in most systems/shells is leaky. I do share your concern however. We want to be careful not to suggest to users that this is secure.

We provide the option of providing a passfile instead of a password. This is probably not enough, though. What if we provide a secure rendering mode on params, and automatically convert the value of any named parameter starting with pass to ***, and ensure that we're not using toString() with data/value semantics? The worst case if we are is that we'll see errors in some places and then we'll have to change the caller to use a specific and more appropriate accessor.

What do you think @alexott ?

**Comment by jshook** [comment]
If it wasn't clear (I left out a key detail), we should make toString() render pass* parameters as redacted.

**Comment by alexott** [comment]
My main afraid was of the situation when people do `nb ..... 2>&1|tee run.log` to capture end results, etc., and then copying it somewhere for analysis...

I'm ok with automatic masking of everything ending on `pass`, although I really thought about declaring a blacklist of properties  (maybe on the activity level) that should be masked...

Regarding the `passfile` option - we have it only for passwords themselves, but not for trustore/keystore, for example. Maybe we need to require this parity for all password-related inputs.

**Comment by jshook** [comment]
I agree. It would be nice for us to start a design guide for developers that includes this type of blanket recommendation. For things like this, we can make it very clear how it should be handled in new drivers.

**Comment by jshook** [comment]
I've filed #1985 as a more general solution to this.
