### ISSUE TITLE
[Feature] Set cql driver default CL to LOCAL_QUORUM

### ISSUE THREAD

**Issue by hemidactylus** [nosqlbench/nosqlbench#1077]
(tested with 5.17.1-release).

The default consistency level for the `cql` driver is LOCAL_ONE, which (besides being generally discouraged on a best-practice basis) does not work when the target database is Astra DB.

To reproduce: provide the required environment variables and run the following workload:

```
scenarios:
  default:
    schema: run driver=cql tags==block:schema threads==1 cycles==UNDEF
    rampup: run driver=cql tags==block:rampup cycles===10 threads=1
bindings:
  my_id: ToHashedUUID()
  name: FullNames()
blocks:
  schema:
    ops:
      create-table:
        stmt: |
          CREATE TABLE IF NOT EXISTS TEMPLATE(keyspace,mykeyspace).mytable
            (
              my_id   UUID PRIMARY KEY,
              name    TEXT
            );
  rampup:
    ops:
      write-in-table:
        stmt: |
          INSERT INTO TEMPLATE(keyspace,mykeyspace).mytable
            (
              my_id,
              name
            )
          VALUES
            (
              {my_id},
              {name}
            );
        params:
          prepared: true
```

Running with
```
nb5 mini-workload default \
 username=${ASTRA_DB_CLIENT_ID} \
 password=${ASTRA_DB_CLIENT_SECRET} \
 secureconnectbundle=${ASTRA_DB_BUNDLE_PATH} \
 keyspace=${ASTRA_DB_KEYSPACE_NAME}
```

there is an error as soon as rampup is entered:
```
18425 ERROR [naivemodel_generate_rampuporders:009] ActivityExceptionHandler Uncaught exception in thread 'naivemodel_generate_rampuporders:009, state[RUNNABLE], notifying executor 'ActivityExecutor~naivemodel_generate_rampuporders': java.lang.RuntimeException: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Provided value LOCAL_ONE is not allowed for Write Consistency Level (disallowed values are: [ANY, ONE, LOCAL_ONE])
```

Currently, the fix is to provide explicitly `cl: LOCAL_QUORUM` at the end of the workload yaml.

But to make it easier for workload to "just work", it'd be better to have LOCAL_QUORUM as (sensible) default CL for the `cql` driver.

**Comment by jshook** [comment]
What about the non-astra case? Should we make this part of the astra specific named scenarios?

**Comment by jshook** [comment]
I believe this is a more sensible default, but is there a way we can avoid breaking existing tests which are using the local default? Since this will not change the effective behavior for systems with RF1, like local functional testing nodes, I'm ok with that scenario.

The main risk for existing tests which have an RF3 scenario is that changing this without an opt-in is that those scenarios may automatically be changed to a different effective workload. This could cause serious impact to existing tests of scale. My recommendation for this, is to *not* change the default, but *do* issue a warning that it will be changed to the default in 5.19.* later this year. Then users will have ample warning that if they want to lock it to a particular value and/or remove the warning, they can simply set the parameter explicitly.

Something like:

    The consistency level was not set directly. It has been set to LOCAL_ONE.
    This does not represent a production-like scenario.
    Beginning in 5.19.0, (due with Java 19 LTS), the default will be changed to LOCAL_QUORUM.
    To silence this warning, simply set the consistency_level directly.

What do you think @hemidactylus ?

**Comment by hemidactylus** [comment]
Agree on the above, it seems there is no way that is unobtrusive (re: existing tests/non-Astra workloads) while not requiring cumbersome inspection in the user-provided options.
All things considered, probably the best course of action is to mention the need to provide Astra-valid `cl` in the docs (and in other quickstart/guides such as [this one](https://awesome-astra.github.io/docs/pages/data/load/nosqlbench/).

**Comment by dave2wave** [comment]
@jshook I'm not sure if this is active, but it does at a minimum point out another [docs need update issue](https://awesome-astra.github.io/docs/pages/data/load/nosqlbench/).

**Comment by dave2wave** [comment]
Is #570 duplicative?

**Comment by dave2wave** [comment]
Handle as described in #570
