### ISSUE TITLE
Question on use of datamappers

### ISSUE THREAD

**Issue by satishrao84** [nosqlbench/nosqlbench#139]
Hi Jonathan,

I see in the code, that there is DateRangeDuring/DateRangeOnOrBefore(or after)/DateRangeFunc.
How would I use this in a data binding portion of the YAML? For example, If I want to generate DateRanges starting after 01/01/2009, I guess I would use DateRangeOnOrAfter - but can you please provide an example of using it? 

Thank You!

**Comment by jshook** [comment]
You might try something like 
```
StartingEpochMillis('2009-01-01 00:00:00'); DateRangeOnOrAfter('day')
```

If you want to quantize the timestamps, then also add something like this:
```
StartingEpochMillis('2009-01-01 00:00:00'); ToMillisAtStartOfDay(); DateRangeOnOrAfter('day')
```

Of course, this is with a default stepping of one millisecond per increment in cycle value. You might want to add a `Mul(3600000)` to the front to advance time by one hour per cycle.

I'll add better docs and examples for these functions to the next feature release.

**Comment by satishrao84** [comment]
Jonathan - thanks But shouldn't I be putting `Add(3600000)` as opposed to  `Mul(3600000)` in the front to increment time by one hour/cycle ?

**Comment by jshook** [comment]
The input to the whole function is the cycle number. Thus `Mul(3600000)` with cycles 0 is 0, 3600000 for cycle 1, 7200000 for cycle 2, and so on. These represent hour increments in milliseconds.
Since the cycle in the input, it represents the seed value for each of the functions you have in the bindings, even though it is incremental. You can use `Hash()` and other functions to get pseudo-random views of data when needed.

**Comment by satishrao84** [comment]
This is very useful! Thank You!
