### ISSUE TITLE
make activityDef and activityDef.getParams consistent across all standard activity params

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#1609]
example: setting "cycles" on the backing store does not properly update the spec models at the activityDef

**Comment by workdone0** [comment]
@jshook Can you tell me how to reproduce this issue?

**Comment by jshook** [comment]
This is related to the way we track activity parameters and expose them for changes dynamically while an activity runs.
In nb 5.21+, this is handled with component tree propogation of change event types ideally. Further, each of these parameters which is part of some parsed state or stateful view needs to use the same reference to the active value, no matter whether it is a primitive or another type. 

Once we have made this work well for cycles (assuming the issue above is still present) it should be documented as a pattern in the dev guidef or dynamic activity parameters.

@workdone0 I think this particular issue may have already been solved. We need to try to reproduce it by setting the parameter on the ActivityDef while an activity is running, and then asserting that the cycles model on that type synchronously updated and consistent. The two places which could get out of sync would be the string version of the cycles spec on the ActivityDef params map, and the Cycles spec model which is also on that type.

**Comment by dave2wave** [comment]
Include in the parsing of ActivityDef to Params conversion to proper lowercase with _ format.

**Comment by dave2wave** [comment]
In `nb-apis/nb-api/src/main/java/io/nosqlbench/nb/api/config/params/ParamsParser.java` the current rule for a valid name is as follows:

```
 * <h3>Names</h3>                                                                                                                                                                      
 * The name of a parameter must appear in raw literal form, with no escaping. A name may not                                                                                           
 * contain spaces, semicolons or equals signs, and may not start with quotes of any kind.                                                                                              
 * Otherwise, there are no restrictions placed on the characters that may appear in                                                                                                    
 * a name. Even escaped characters are allowed.                                                                                                                                        
```

This is the code that parses ActivityDefs. It looks like one spot to enforce more limited character set rules. There are two approaches. Review the KeySet produced and/or limit the acceptable characters. We will need to review the KeySet since not every time these used will be parsed here.

Either way there are two categories of chars to exclude:
1. Symbols like "-" that are problems for downstream systems like metrics. Also colon, astericks, parentheses, and brackets may be problematic.
2. Always convert to lower case. Do we want to officially not care about exact matching of case? Or, should names with UpperCase be illegal?

**Comment by dave2wave** [comment]
We will analyze ConfigModels for parameter name consistency.

**Comment by dave2wave** [comment]
It looks to me like this is `ActivityDef` and `ActivityDef.getParams` are in fact consistently used in the code.

We may need to add more Parameters which are explicitly retrieved by `ActivityDef.getParams().get...`
