### ISSUE TITLE
Allow easy setting of environment variables for scenarios

### ISSUE THREAD

**Issue by jshook** [nosqlbench/nosqlbench#2033]
Sometimes a user needs to set an environment variable, for example when this is the only way offered by a vendor to configure something. This should be implemented as a simple command, like setenv.

**Comment by dave2wave** [comment]
You could do this:

If you want to fork the **current Java process** with a modified environment, you can use `ProcessBuilder` to re-launch the same Java application in a new subprocess. By configuring the `ProcessBuilder` to launch the same JAR or main class, you effectively "fork" the current process with a different environment.

Here’s how to do it:

1. **Determine the current Java command**:
   You need to know how to launch the current Java program, including the JAR file or classpath and main class name.

2. **Set up `ProcessBuilder`**:
   Use `ProcessBuilder` to set the environment variables for the new process and specify the command to relaunch the current application.

3. **Pass any necessary arguments**:
   If the original process received arguments, you can pass them to the forked process.

Here’s a complete example:

```java
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Arrays;
import java.util.Map;

public class ProcessForkWithEnv {
    public static void main(String[] args) {
        // Check if the process was started as a fork (e.g., with custom environment)
        boolean isForkedProcess = Arrays.asList(args).contains("--forked");

        if (isForkedProcess) {
            // This code will only run in the forked process
            System.out.println("Forked process started with modified environment.");
            System.out.println("MY_CUSTOM_VAR: " + System.getenv("MY_CUSTOM_VAR"));
            return;
        }

        try {
            // Set up the ProcessBuilder to re-launch the current application
            ProcessBuilder processBuilder = new ProcessBuilder(
                // Use the Java executable to launch the application
                System.getProperty("java.home") + "/bin/java",
                "-cp", System.getProperty("java.class.path"),  // Set the classpath
                ProcessForkWithEnv.class.getName(),             // Main class to execute
                "--forked"                                     // Custom argument to identify forked process
            );

            // Modify the environment for the forked process
            Map<String, String> env = processBuilder.environment();
            env.put("MY_CUSTOM_VAR", "HelloWorld");

            // Start the forked process
            Process process = processBuilder.start();

            // Capture output from the forked process
            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            String line;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }

            // Wait for the process to finish
            int exitCode = process.waitFor();
            System.out.println("Forked process exited with code: " + exitCode);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

### Explanation

1. **Check for Forked Process**: 
   - The main class checks if it was launched with the `--forked` argument. If present, it means the code is running in the forked process, where it prints the environment variable.
   
2. **Set up `ProcessBuilder` to Fork the Current Process**: 
   - The `ProcessBuilder` uses the current Java executable (`System.getProperty("java.home") + "/bin/java"`), classpath (`System.getProperty("java.class.path")`), and main class name (`ProcessForkWithEnv.class.getName()`).
   - It also adds `--forked` to the arguments so that the forked process knows it’s in a forked environment.

3. **Modify Environment**: 
   - `env.put("MY_CUSTOM_VAR", "HelloWorld")` modifies the environment for the new process.

4. **Capture Forked Process Output**:
   - Reads and displays output from the forked process, useful for debugging or logging.

### Running and Testing

When you run this code:
1. The initial process starts and detects it’s not a forked process.
2. It creates a new `ProcessBuilder`, sets environment variables, and forks the process with `--forked`.
3. The forked process starts, detects the `--forked` flag, and outputs the custom environment variable.

This effectively creates a new instance of the current application with a modified environment, simulating a fork with new environment variables.

**Comment by dave2wave** [comment]
The only way to do this properly is to some package this in the `nb5` script.

**Comment by dave2wave** [comment]
This is not really feasible without maneuvers which are best done by setting the environment variables in advance
