### ISSUE TITLE
Nosqlbench should not guess the workload extension if it is provided

### ISSUE THREAD

**Issue by Gerrrr** [nosqlbench/nosqlbench#344]
**Describe the bug**

Nosqlbench tries to match workload extensions even when the extension is already specified:

```
✗ nb start workload=https://gist.githubusercontent.com/Gerrrr/path/to/workload.yaml
   4188 WARN  [scenarios:001] ResolverForURL Unable to find content at URI 'https://gist.githubusercontent.com/Gerrrr/path/to/workload.yml', this often indicates a configuration error.
```

The warning above complains that `workload.yml` does not exist.

**What was Expected**

Nosqlbench should not try to guess the extension if it is already provided. If the filename contains the extension and the file does not exist, it should just fail with an error.

**Comment by marianne-manaog** [comment]
Hi @jshook, FYI: I am experiencing the same issue when running tests using `workload` key. While I provide a `.yaml` file it looks for a `.yml` file and therefore does not find it.

**Comment by jshook** [comment]
I've updated the NBIO logic lately to not do advanced searches before trying the most obvious location, which takes precedence. This doesn't change the original issue, as I think it was having trouble finding the `.yaml` version, IIRC. However, it will look preferentially for only one matching file when it is clearly a specific path, rather than looking for possible matches and asserting there is only one.
