### ISSUE TITLE
This parameter   "--progress console:1s"   Can not work

### ISSUE THREAD

**Issue by QWQyyy** [nosqlbench/nosqlbench#352]
**Describe the bug**
This parameter   "--progress console:1s"   Can not work

**To Reproduce**
I can not saw the print in the cmd windows.

**What was Expected**
I do not kown why

**Additional context**
My env:
Cassandra 3.1.11 or 4.0.1
CentOS 7.6
And use you now project code

It very hard work, pls help me ... QWQ

**Comment by jshook** [comment]
@QWQyyy Thanks for the bug report. It has been fixed for the next release today.
The issue was this:
There is some logic to redirect progress to logonly automatically when the log are going to console at INFO or higher, so that there is no annoying duplication of the output. The logging level check was backwards.
I've tested that it works with and without -v such that there is at least one active progress channel in either case.

**Comment by QWQyyy** [comment]
well notes,thank U.
